server:
  ssl:
    key-store: file:C:/Users/Korisnik/CertificatesV2/chatserver1store.jks
    key-store-password: rootca
    key-alias: localhost
    key-password: root
    enabled: true
  port: 8445
spring:
  security:
    user:
      name: admin
      password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest